### PR TITLE
Allow vswhere to locate Visual Studio Build Tools

### PR DESCRIPTION
**Pull request by hipolipolopigus**

### CODE REVIEW

**Comment by TheOneRing** [comment]
Sounds cool, and craft was fully functional with just a Build Tools setup?

**Comment by hipolipolopigus** [comment]
@TheOneRing Yes, at least with Build Tools 2017 15.3.5. I don't maintain a full VS installation, however, so it might be prudent to also add a flag like ` -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64` to ignore products without the MSVC compiler, as per [the vswhere wiki](/Microsoft/vswhere/wiki/Find-VC).

**Comment by TheOneRing** [comment]
Sounds reasonable.
Can you test it with the `-requires` parameter?

**Comment by hipolipolopigus** [comment]
The proposed `-requires` parameter behaved as expected. When VS was installed, but lacking C++ components, vswhere detected it unless the `-requires` parameter was specified.

Specifying the `-requires` parameter seems to conflict with `-legacy`. Despite the following error message, `-products` with the wildcard does not seem to cause issues:
```
Error 0x57: The "legacy" parameter cannot be specified with either the "products" or "requires" parameter.
```
I'm unable to test or verify via cursory searches whether `-products *` includes products covered by `-legacy`, which may mean a loss of compatibility with older VS installations. If that is acceptable, then I'd propose the final parameters look like the following:
```
-property installationPath -nologo -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64
```
This will allow vswhere to both detect all MSVC installations, whether from Build Tools or VS, and ignore Build Tools or VS installations which do not contain an MSVC compiler.

**Comment by hipolipolopigus** [comment]
Additionally, an installation log with my modifications (and modifications to point to my fork) can be found in [this gist](https://gist.github.com/hipolipolopigus/e81ab0d17763d9f1381664220e199c6f). After modifying the additional clone of `kde:craft`, running `craftenv.ps1` works as expected.

**Comment by TheOneRing** [comment]
Ok looks reasonable, pls only set the values when a non legacy version is selected (2017+)

**Comment by TheOneRing** [comment]
Looks good.
I will apply it the next time I'm on my pc, using the web interface isn't supported for KDE projects.

**Comment by TheOneRing** [comment]
Thanks for the contribution, I squashed the commit and applied it in https://github.com/KDE/craft/commit/7fa874f68d8eb493430dce5fe494d25f4903e285

**Pull request closed without merging**
